// 



export const DataSpanish =[
    // {
    //     id : 0,
    //     tipo : ["","",""],
    //     titulo : lorem,
    //     imagenes : ["", "", "",],
    //     textDetalles : "",
    //     precio : "",
    //     horario : "",
    //     direccion : "",
    //     linkDireccion : "",
    //     vr : "" ,
    //     correo : "",
    //     web : "",
    //     telefono : ["",""],
    //     puntuacion : "",
    //     opiniones : "",
    //     usuarios : ["Juan   👤","Brailer   👤","Jenny   👤"],
    //     comentarios : ["","","",],
    //     historia : ["",""], // imagenMenu : [""], // informacion : "",
    //     BtnConoce : "",
        
    // }
    /* - - - - Cultura - - - -  */
    { //19
        id : 1,
        tipo : "cultural",
        titulo : "Cementerio Museo de San Pedro",
        textDetalles :"Constituye parte integral del patrimonio cultural y arquitectónico del arte funerario de Medellín, guardando el sepelio de grandes personajes de la Nación. Hoy en día se perfila como un difusor de colecciones de arte local y nacional, con espectáculos de narración oral, obras de teatro y danza.",
        precio : "Entrada Gratuita",
        horario : "",
        direccion : "Cra. 51 #68-68, Aranjuez, Medellín, Aranjuez, Medellín, Antioquia ",
        linkDireccion: "https://maps.app.goo.gl/epqov7HApFUGNyNU6",
        vr : "https://www.google.com/maps/@6.265606,-75.5612699,3a,75y,220.88h,99.81t/data=!3m8!1e1!3m6!1sAF1QipMgziLA7Le4hO3KkP23LafrOqhU0fdncc0zZopI!2e10!3e11!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipMgziLA7Le4hO3KkP23LafrOqhU0fdncc0zZopI%3Dw203-h100-k-no-pi0-ya33.368584-ro-0-fo100!7i10240!8i5120?entry=ttu",
        correo :"cementerio.museo@cementeriosanpedro.org.co",
        Web :"https://cementeriosanpedro.org.co/",
        telefono :["(+57) 604 516 7650","(+57) 604 540 3450"], 
        puntuacion : "4.0 ★ ★ ★ ★",
        opiniones : "632 opiniones",
        usuarios : ["danial   👤","Julieta   👤","Luis   👤",], /* entidad  */
        comentarios : [ "Me encanto asistir a la visita guiada que ofrecen los domingos, manejan dos horarios 2 y 3:30 de la tarde debes hacer reserva previa por WhatsApp. El recorrido es muy interesantes el cementerio esta muy organizados. La guia hablaba con mucha prudencia y elocuencia, super recomendado.",
                        "Clásico lugar de la ciudad medellin, en este lugar reposa los muertos de las comunas de medellin, además,  de personajes importantes de la cultura antioqueña y colombiana.",],
                     
        historia : ["Fundado el 22 de septiembre de 1842 como el primer cementerio privado de la ciudad, cuando la población tenía unos 9,000 habitantes y apenas 16 años desde que se convirtió en la nueva capital de Antioquia. El cementerio fue fundado por destacadas familias de la Villa debido a la falta de un cementerio adecuado para sus seres queridos.",
        "por iniciativa de Pedro Uribe Restrepo se reunieron en junta varios caballeros de las más prestantes familias de la Villa de la Candelaria, y acordaron la fundación de un nuevo cementerio, al ver la carencia de uno digno para sus familias, puesto que el Cementerio de San Lorenzo, que se había fundado en enero de 1828."],
        BtnConoce : "https://es.wikipedia.org/wiki/Bas%C3%ADlica_de_Nuestra_Se%C3%B1ora_de_la_Candelaria_(Medell%C3%ADn)",
    },  
    {  //19
        id : 2,
        imagenes:["../Multimedia/Lugares/cultura/Palacio Rafael Uribe Cultura/PalacioUribe.jpg",
        "../Multimedia/Lugares/cultura/Palacio Rafael Uribe Cultura/PalacioUribe2.jpg",
        "../Multimedia/Lugares/cultura/Palacio Rafael Uribe Cultura/PalacioUribe3.jpg"],
        tipo : "cultural",
        titulo : "Palacio de la cultura Rafael Ubire",
        imagenes : ["../Multimedia/Lugares/cultura/Palacio Rafael Uribe Cultura/PalacioUribe.jpg", "../Multimedia/Lugares/cultura/Palacio Rafael Uribe Cultura/PalacioUribe2.jpg", "../Multimedia/Lugares/cultura/Palacio Rafael Uribe Cultura/PalacioUribe3.jpg"],
        textDetalles : "Arteria en el corazón de la ciudad, sede actual del Instituto de Cultura y Patrimonio de Antioquia, el Palacio Rafael Uribe contiene el archivo Histórico de Antioquia, la Biblioteca y la Fonoteca Departamental, la Sala de Patrimonio Artístico, la Galería de Arte entre otros.",
        precio : "Entrada Gratuita",
        //prueba para horarios //
        horario: '<p> Lunes a Viernes <br>9a.m. – 5:30p.m.</p><p>Sabado a Domingo <br>10a.m. – 3:30p.m.</p>',
        // --------------//
        linkDireccion : "https://maps.app.goo.gl/ZgmcHCCCzsbindQj6",
        direccion : "Carrera 51 #52 01 Medellín Antioquia 050012, Medellín, Antioquia",
        vr : "https://www.google.com/maps/@6.2517372,-75.5682648,3a,90y,155.62h,90.02t/data=!3m8!1e1!3m6!1sAF1QipNcXHf3v2RKNM4PRb1Cdpz6oHvgJF5yGnKn1rUL!2e10!3e11!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipNcXHf3v2RKNM4PRb1Cdpz6oHvgJF5yGnKn1rUL%3Dw203-h100-k-no-pi-0-ya179.46317-ro0-fo100!7i8704!8i4352?entry=ttu",
        correo : "",
        web : "http://www.culturantioquia.gov.co/",
        telefono : "43209780",
        puntuacion : "4,7 ★ ★ ★ ★",
        opiniones : "2313 Opiniones",
        usuarios : ["Fredy   👤","Pelusa   👤","Manuela   👤"],
        comentarios : ["Arquitectura increíble, patrimonio nacional de historia sobre los artesanos de la madera y interesantes salas de creatividad artesanal con diferentes materiales.   Linda panorámica del centro de la ciudad con el edificio Coltejer y el desarrollo en movilidad con el Metro de Medellin.",
        "Un lugar con una historia y arquitectura sin igual. Perfecto para compartir en familia, aprender sobre la historia de Medellín y sacar hermosas fotos. El arte que se vive allí, te hincha el corazón de alegría.",
        "Un excelente lugar para conocer parte de la historia de la ciudad, además de disfrutar de sus exposiciones artísticas. Lamentablemente los fines de semana cierran temprano, por esto se recomienda asistir en horas de la mañana."],
        historia : ["Inaugurado el 26 de marzo de 1925, sirvió como sede de la Gobernación de Antioquía.", 
        "El arquitecto Agustín Goovaerts comenzó a trabajar en el proyecto en 1920, sólo se completó una cuarta parte debido a la crisis económica,  se enfrentaron a recortes presupuestales. La obra se suspendió en 1938, y no se terminó hasta 1970, aunque solo se siguió la mitad del diseño original de Goovaerts. En 1987, la administración departamental se trasladó, y el edificio adoptó su nombre actual en honor a Rafael Uribe Uribe."],
        BtnConoce : "https://es.wikipedia.org/wiki/Bas%C3%ADlica_de_Nuestra_Se%C3%B1ora_de_la_Candelaria_(Medell%C3%ADn)",
        
    },
    {  //19
        id : 3,
        tipo : "cultural",
        titulo : "Museo Casa de la Memoria",
        imagenes : ["../Multimedia/Lugares/cultura/Museo Casa de la Memoria/Museo.jpg",
        "../Multimedia/Lugares/cultura/Museo Casa de la Memoria/Museo2.jpg",
        "../Multimedia/Lugares/cultura/Museo Casa de la Memoria/Museo3.jpg"],
        textDetalles : "En el Museo de la Memoria en Colombia, las víctimas del conflicto armado se unen para crear y preservar sus memorias a través de iniciativas y resistencias. Estas acciones incluyen la construcción colectiva de memorias y la reparación simbólica. El museo se convierte en un lugar donde las comunidades se reconocen mutuamente y trabajan juntas en la construcción de la paz utilizando expresiones artísticas y culturales.",
        precio : "Entrada Gratuita",
        horario : "",
        direccion : "Parque Bicentenario, Cl. 51 #36-66, La Candelaria, Medellín, La Candelaria, Medellín, Antioquia",
        linkDireccion:"https://maps.app.goo.gl/2GxEWaRZ5NNsoz3b7",
        vr : "https://www.google.com/maps/@6.2470175,-75.5578755,3a,75y,180.79h,106.7t/data=!3m8!1e1!3m6!1sAF1QipNW9X5s7qBQ9MJAXHbkIc1Yf66drxdDYHyG4Zmx!2e10!3e11!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipNW9X5s7qBQ9MJAXHbkIc1Yf66drxdDYHyG4Zmx%3Dw203-h100-k-no-pi-0-ya163.64578-ro0-fo100!7i8000!8i4000?hl=es&entry=ttu",
        correo : "contacto@museocasadelamemoria.gov.co",
        web : "https://www.museocasadelamemoria.gov.co/",
        telefono : "(604) 5202020",
        puntuacion : "4.7 ★ ★ ★ ★ ",
        opiniones : "5.784 opiniones",
        usuarios : ["Juan   👤","Brailer   👤","Jenny   👤"],
        comentarios : ["Un sitio extraordinario para ver el lado que todos quieren ocultar de la historia de nuestro país.",
        "Es una experiencia muy interesante y conmovedora que nos recuerda todo el dolor que causa el conflicto armado y todo lo que vivieron las personas que lucharon en contra de el.",
        "Visitar este museo es una experiencia qué no te puedes perder, si andas en Medellín. Es un espacio verdaderamente conmovedor y de mucha reflexión. La entrada no tiene costó."],
        historia : ["La Casa de la Memoria, se creó en la década de 2000 como respuesta a la necesidad de conmemorar a las víctimas del conflicto armado en Colombia. Fue inaugurada el 22 de octubre de 2009 en un edificio restaurado para albergar exposiciones y actividades relacionadas con la memoria histórica.",
        "El Programa de Atención a Víctimas del Conflicto Armado se encarga del proyecto museológico y la Empresa de Desarrollo Urbano (EDU) diseña el proyecto arquitectónico para ubicarlo en el parque Bicentenario."],
        BtnConoce : "https://es.wikipedia.org/wiki/Bas%C3%ADlica_de_Nuestra_Se%C3%B1ora_de_la_Candelaria_(Medell%C3%ADn)",
        
    },
    //---------------Historia------------------//
    {  //19
        id : 4,
        tipo : "historia",
        titulo : "Basílica de Nuestra Señora de la Candelaria",
        imagenes : ["../Multimedia/Lugares/historia/basilica/basilica.jpg",
         "../Multimedia/Lugares/historia/basilica/basilica4.jpg",
          "../Multimedia/Lugares/historia/basilica/Basilica-candelaria.jpeg",],
        textDetalles : "Para los amantes de la historia y la religión, está Basílica representa el corazón e inicio de los Antioqueños en el Catolicismo.",
        precio : "Sin Costo Alguno",
        horario : "",
        direccion : "Cl. 50 #49 - 112, La Candelaria, Medellín, La Candelaria, Medellín, Antioquia",
        linkDireccion : "https://www.google.com/maps/@6.250017,-75.5675647,3a,75y,133.73h,116.15t/data=!3m8!1e1!3m6!1sAF1QipPjFEMdLkodAsIEaezawBpdEL7JBkAjlublrvF6!2e10!3e11!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipPjFEMdLkodAsIEaezawBpdEL7JBkAjlublrvF6%3Dw203-h100-k-no-pi0-ya336.6846-ro-0-fo100!7i8000!8i4000?entry=ttu",
        vr : "https://www.google.com/maps/@6.2500529,-75.5677093,3a,90y,112.35h,108.83t/data=!3m10!1e1!3m8!1sDc0Y7PA77xtnSK-g-G7mBw!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DDc0Y7PA77xtnSK-g-G7mBw%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D97.32656%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656!9m2!1b1!2i27?hl=es&entry=ttu",
        correo : "",
        web : "",
        telefono : ["604-234907",""],
        puntuacion : "4,6 ★ ★ ★ ★",
        opiniones : "496 opiniones",
        usuarios : ["Camila   👤","Julian   👤","Jecenia   👤"],
        comentarios : ["Es una iglesia hermosa ubicada en el centro de la ciudad. Su estilo barroco agradable a la vista y con hermoso acabado en ladrillos la hacen acogedora.",
        "Es hermosa. Y aún más lindo poder compartir con Dios nuestro señor Jesucristo y su santísima madre María.",
        "En pleno corazón de la ciudad de Medellín se encuentra esta iglesia, dedicada a nuestra señora de la Candelaria. Con obras de arte sacro que datan de tiempos de la colonia, vale la pena visitar.",],
        historia : ["La Basílica Menor de Nuestra Señora de La Candelaria de Medellín es la primera parroquia de la ciudad. Su primera construcción, en madera y techo de paja, fue emprendida por el cura Don Juan Gómez de Ureña, en 1649, 26 años antes de que Medellín fuera nombrada como villa, su construcción inicial fue muy inestable.",
        "Se dedicó a Nuestra Señora de la Candelaria, advocación de especial devoción para los españoles y particularmente para los marinos que cruzaron el Atlántico para llegar al Nuevo Mundo."],
        BtnConoce : "https://es.wikipedia.org/wiki/Bas%C3%ADlica_de_Nuestra_Se%C3%B1ora_de_la_Candelaria_(Medell%C3%ADn)",
    },
    {  //19
        id : 5,
        tipo : "historia",
        titulo : "Museo el Castillo",
        imagenes : ["../Multimedia/Lugares/historia/MuseoCastillo/MuseoC3.jpg",
         "../Multimedia/Lugares/historia/MuseoCastillo/MuseoC2.jpeg",
          "../Multimedia/Lugares/historia/MuseoCastillo/museo5.png",
          "../Multimedia/Lugares/historia/MuseoCastillo/MuseoC.jpeg"],
        textDetalles : "Bienvenido al Principal representante del Arte Gótico Medieval de la ciudad. Ofrece exposiciones permanentes de objetos en porcelana y cristal, vitrales, gobelinos, antigüedades, pinturas  y esculturas, entre otros.",
        precio : "$20.000 (Costo de la entrada)",
        horario : "",
        direccion : "Cl. 9 Sur #32-269, El Poblado, Medellín, El Poblado, Medellín, Antioquia",
        linkDireccion : "https://maps.app.goo.gl/zrWwEjiKmToj9fpH8",
        vr : "https://www.google.com/maps/@6.1903392,-75.5700119,2a,75y,104.62h,102.99t/data=!3m9!1e1!3m7!1spnrHEygtO2Vu1MINEUDfag!2e0!7i13312!8i6656!9m2!1b1!2i23?entry=ttu",
        correo : "info@museoelcastillo.org",
        web : "http://www.museoelcastillo.org/",
        telefono : ["+57 4 266 09 00",""],
        puntuacion : "4,7 ★ ★ ★ ★",
        opiniones : "12.376 Opiniones",
        usuarios : ["Jimmy   👤","Carlos   👤","Carolina   👤"],
        comentarios : ["Es mi museo favorito. Es una casa donde te cuentan la historias de las personas ricas que vivían ahí. Les recomiendo que vayan. Tiene una cafetería adentro de el área. También cuenta con un jardín muy bonito para tomarse fotos. Vale la pena ir. Cuando uno entra a área de el museo es como entrar a otro mundo.",
        "Es sencillamente hermoso, mágico!!! Me encanta este lugar, su historia.. literal es como sentirse en un cuento desde que vas entrando.. suuuper recomendado !!!",
        "Es un lugar maravilloso. Es histórico, hay cafetería, se realizan eventos.",],
        historia : ["La edificación, inspirada en los castillos del Valle del Loira en Francia, fue construido en 1930 al estilo gótico medieval por la primera oficina de arquitectos de Medellín, H. M. Rodríguez, como casa de campo del señor José Tobón Uribe, médico y fundador de la Farmacia Pasteur, pionera en el Medellín de la época. En 1942, lo adquirió el filántropo antioqueño Diego Echavarría Misas, junto a su esposa Benedikta Zur Nieden, quienes ampliaron y decoraron sus espacios con valiosas obras de arte de distintas corrientes, épocas y lugares de Europa y América, para convertirlo en un centro cultural al alcance de todos.",""],
        BtnConoce : "https://es.wikipedia.org/wiki/Bas%C3%ADlica_de_Nuestra_Se%C3%B1ora_de_la_Candelaria_(Medell%C3%ADn)",
    },
    {  //19
        id : 6,
        tipo : "historia",
        titulo : "Parque Berrío",
        imagenes : ["../Multimedia/Lugares/historia/parkBerrio/Pberrio.jpg",
         "../Multimedia/Lugares/historia/parkBerrio/Pberrio2.jpg",
          "../Multimedia/Lugares/historia/parkBerrio/Pberrio3.jpg",
        "../Multimedia/Lugares/historia/parqueberrio/berrio3.png"],
        textDetalles : "Un ícono urbano, quizá el más históricamente significativo de la urbe, donde los antioqueños han confluido y considerado por generaciones como principal lugar de encuentro y como referente de su ciudad frente a visitantes y foráneos.",
        precio : "(Sin Costo Alguno)",
        horario : "",
        direccion : "Cl. 50, La Candelaria, Medellín, La Candelaria, Medellin, Antioquia",
        linkDireccion : "https://maps.app.goo.gl/eebUpUqaBEtkeqyP7",
        vr : "https://www.google.com/maps/@6.250095,-75.5680783,3a,75y,6.27h,103.09t/data=!3m8!1e1!3m6!1sAF1QipP_9FHa4CtVo3QN1q9X4qOb3at6Um56CC6ZCuXK!2e10!3e11!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipP_9FHa4CtVo3QN1q9X4qOb3at6Um56CC6ZCuXK%3Dw203-h100-k-no-pi-0-ya228.73744-ro0-fo100!7i6080!8i3040?entry=ttu",
        correo : "",
        web : "http://www.medellin.gov.co/",
        telefono : ["",""],
        puntuacion : "4,1 ★ ★ ★ ★",
        opiniones : "29.924 Opiniones",
        usuarios : ["Tejada   👤","Pedro   👤","Pepito   👤"],
        comentarios : ["Buen lugar emblemático de Medellín, lindo y agradable. Los músicos y los bailes que evocan la época de los abuelos, hacen a su vez un contraste con la actualidad, dando como tal un matiz de expresiones culturales sanas que hacen muy acogedor el lugar. Muy recomendado!",
        "Muy bonito y grande, chevere tomarse fotos en la plaza de botero, hay varios restaurantes y ahí mismo esta el metro y hay una parada de bus que viene y va al aeropuerto.. lo malo es que esta lleno de mucha gente sin hogar, o gente de la vida alegre pero quitando eso es un sitio chevere.",
        "",],
        historia : ["La historia de este parque está estrechamente ligada con la del Templo de La Candelaria, construido inicialmente en 1649. La Plaza Principal, como se le llamó en un comienzo, era la antesala de la iglesia, y allí coincidían los feligreses antes y después de la eucaristía.","Entre 1784 y 1892, funcionó allí el mercado público, y también fue este sitio escenario de ejecuciones y grandes actos públicos y políticos. Como en todas las grandes ciudades de influencia hispánica, las familias más prestantes vivían alrededor de esta plaza."],
        BtnConoce : "https://es.wikipedia.org/wiki/Bas%C3%ADlica_de_Nuestra_Se%C3%B1ora_de_la_Candelaria_(Medell%C3%ADn)", 
    },
    //----------------------Naturaleza---------------------//
    {  //19
        id : 7,
        tipo : "naturaleza",
        titulo : "Jardin Botánico",
        imagenes : ["../Multimedia/Lugares/naturaleza/Botanico/Botanico.webp",
        "../Multimedia/Lugares/naturaleza/Botanico/Botanico3.jpg",
        "../Multimedia/Lugares/naturaleza/Botanico/Botanico2.jpeg",],
        textDetalles : "El Jardín Botánico de Medellín Joaquín Antonio Uribe es un hermoso espacio de 13.2 hectáreas con más de 1,000 especies vivas y 4,500 individuos. Destaca por su Orquideorama y su colección de orquídeas. Además de ser una atracción turística destacada en la región, es un centro de cultura, educación ambiental y botánica importante.",
        precio : "(Entrada Gratuita)",
        horario : "",
        direccion : "Cl. 73 #51d-14, Aranjuez, Medellín, Aranjuez, Medellín, Antioquia",
        linkDireccion : "https://maps.app.goo.gl/QQ8AnAahBGJ38Vsw6",
        vr : "https://www.google.com/maps/@6.2705435,-75.56365,3a,90y,230.23h,100.88t/data=!3m11!1e1!3m9!1sAF1QipOl0kxmbcKRccbTau16_iqnFgcN93gvZjYuoUsl!2e10!3e11!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipOl0kxmbcKRccbTau16_iqnFgcN93gvZjYuoUsl%3Dw203-h100-k-no-pi0-ya276.4154-ro-0-fo100!7i6144!8i3072!9m2!1b1!2i27?entry=ttu",
        correo : "comunicaciones@jbotanico.org",
        web : "http://www.botanicomedellin.org/",
        telefono : ["604 4445500",""],
        puntuacion : "4,7 ★ ★ ★ ★",
        opiniones : "39.486 Opiniones",
        usuarios : ["Marisol   👤","Diana   👤","Andrea   👤"],
        comentarios : ["Verdaderamente hermoso, un lugar especial para conectar con la naturaleza, hacer picnic y pasear un rato. Me encantó ❤️",
        "Es un lugar hermoso y tranquilo, de ingreso gratuito. Cuenta con vivero, y un bello mariposario (la entrada vale $6000 y $3000 con factura de servicios públicos) puedes preguntar orientaciones a la gente que trabaja allí, son muy amables.",
        "Hermosamente natural, excelente conexión con la naturaleza. El orquideorama es una obra arquitectónica imponente, sus instalaciones están impecables. 100% recomendado",],
        historia : ["Hace más de un siglo, a finales del (XIX), la historia del Jardín Botánico de Medellín comenzó en la finca recreativa ´El Edén´,  la finca era alquilada a familias de una ciudad que entonces tenía 40.000 habitantes. Era una especie de “estadero”, parecido a los de hoy, reconocido como centro de esparcimiento, a donde llegaban las familias a pasar el rato en los baños, mientras disfrutaban de la gastronomía popular.",""],
        BtnConoce : "https://es.wikipedia.org/wiki/Jard%C3%ADn_bot%C3%A1nico_de_Medell%C3%ADn",
        
    },
    {  //19 
        id : 8,
        tipo : "naturaleza",
        titulo : "Parque Arví",
        imagenes : ["../Multimedia/Lugares/naturaleza/Parque Arvi/Arvi3.jpg","../Multimedia/Lugares/naturaleza/Parque Arvi/Arvi2.jpeg","../Multimedia/Lugares/naturaleza/Parque Arvi/Arvi.jpeg",
        ],
        textDetalles : "Es un impresionante parque natural ubicado en las montañas cercanas a Medellín, es un lugar popular para escapar del ajetreo de la ciudad y disfrutar de la naturaleza. Ofrece a los visitantes la oportunidad de explorar la naturaleza, hacer senderismo, andar en bicicleta, disfrutar de la belleza del paisaje y participar en actividades al aire libre.",
        precio : "$5.200 - $23.000",
        horario : "",
        direccion : "Via a Piedras Blancas, Medellín, Antioquia",
        linkDireccion : "https://maps.app.goo.gl/wHo7Dnnh4mj9EkcJA",
        vr : "https://www.google.com/maps/@6.2814291,-75.5026375,3a,52.4y,119.57h,93.59t/data=!3m8!1e1!3m6!1sAF1QipMNkXbAXN7o2DDOQPDib1Ym41hCiNoFmroCkYDy!2e10!3e11!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipMNkXbAXN7o2DDOQPDib1Ym41hCiNoFmroCkYDy%3Dw203-h100-k-no-pi-0-ya319.06085-ro0-fo100!7i8704!8i4352?entry=ttu",
        correo : "corporacion@parquearvi.org",
        web : "https://www.parquearvi.org/",
        telefono : ["604 4442979",""],
        puntuacion : "4,7 ★ ★ ★ ★",
        opiniones : "21.374 opiniones",
        usuarios : ["Santiago   👤","Eyder   👤","Parra   👤"],
        comentarios : ["Un lugar natural muy fresco, rodeado de mucha vegetación y linda flora. Los productos que hay en el mercado inicial en la plazoleta central del parque Arví son muy buenos y de gran calidad. Después de un sendero se encuentra una zona de comercio, café, baños (tienen un valor de 1.000) y algunas oficinas.",
        "Lugar espectacular, rodeado de bosques verdes y entretenidos senderos. Perfecto para compartir con familia y salir a respirar aire puro, desconectarse de la ciudad.",
        "Me gustó mucho la caminata, es una linda experiencia pero bastante agotadora físicamente de todos modos muy recomendable. La guía turística nos contó muchas historias sobre el pasado del lugar y sobre la fauna y flora",],
        historia : ["Descubierto en 1541 por el mariscal español Jorge Robledo. Según un cronista, el Mariscal encontró caminos de roca cortada y buscó una ciudad. Sin embargo, por más que caminó, no pudo encontrar una ciudad, sólo viejos edificios destruidos. En el siglo XX, debido al crecimiento de la población, se creó la Corporación Parque Arví en 2007. Esta organización, conformada por entidades públicas y privadas, tenía como objetivo desarrollar un espacio de recreación para los habitantes del Valle de Aburrá y Rionegro.",""],
        BtnConoce : "https://es.wikipedia.org/wiki/Bas%C3%ADlica_de_Nuestra_Se%C3%B1ora_de_la_Candelaria_(Medell%C3%ADn)",
        
    },
    {  //19
        id : 9,
        tipo : "naturaleza",
        titulo : "Cerro el Picacho",
        imagenes : ["../Multimedia/Lugares/naturaleza/Picacho/Picacho2.jpg",
         "../Multimedia/Lugares/naturaleza/Picacho/Picacho.jpg", 
         "../Multimedia/Lugares/naturaleza/Picacho/Picacho3.jpg",],
        textDetalles : "El EcoParque Cerro El Picacho es un parque natural ubicado al noroccidente de la ciudad de Medellín. Es una formación natural extraordinaria en su forma, cuyo maestro fue la naturaleza.",
        precio : "(Sin Costo Alguno)",
        horario : "",
        direccion : "Picachito, Medellín, San Cristóbal, Medellín, Antioquia",
        linkDireccion : "https://maps.app.goo.gl/iJQLA9Nd6qP4ddgX8",
        vr : "https://www.google.com/maps/@6.3039995,-75.5871686,3a,90y,355.21h,75.58t/data=!3m8!1e1!3m6!1sAF1QipMkemdMzG5eHIrPH6x1X0iN-MOk7bYyWIkcQ3Yk!2e10!3e11!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipMkemdMzG5eHIrPH6x1X0iN-MOk7bYyWIkcQ3Yk%3Dw203-h100-k-no-pi0-ya105.89093-ro0-fo100!7i8192!8i4096?entry=ttu",
        correo : "",
        web : "",
        telefono : ["3234338337",""],
        puntuacion : "4,6 ★ ★ ★ ★",
        opiniones : "496 opiniones",
        usuarios : ["Alejo   👤","Susana   👤","Karol   👤"],
        comentarios : ["Las vistas desde la cima son espectaculares, el cristo se conserva muy bien y el clima es bastante reconfortante.",
        "Un buen lugar si te gusta el eco turismo , desde aqui puedes ver todo el norte de la ciudad, es muy popular este sitio tanto que existe una canción que se llama yo vivo en el picacho en general pude ver una linda vista desde aqui.",
        "Es un lugar poco visitado por turistas, ya que no lo ofrecen comúnmente en los tours. Muy linda vista, espectacular si quieres salir un poco de la ciudad.",],
        historia : ["Desde el siglo XVIII hasta principios del XX, El Picacho fue un lugar de paso del camino real que venía desde Santa Fe de Antioquia en el río Cauca hacia la pequeña villa de la Candelaria de Medellín. En 1936, Monseñor Félix, fundador de la Universidad Pontificia Bolivariana, propuso a la comunidad campesina y los habitantes del sector, ubicar en la cima del Cerro un Cristo Salvador traído de Europa, con el fin de convertir este lugar en un nuevo referente religioso.","Se dedicó a Nuestra Señora de la Candelaria, advocación de especial devoción para los españoles y particularmente para los marinos que cruzaron el Atlántico para llegar al Nuevo Mundo."],
        BtnConoce : "https://es.wikipedia.org/wiki/Bas%C3%ADlica_de_Nuestra_Se%C3%B1ora_de_la_Candelaria_(Medell%C3%ADn)",   
    },
    //---------------------Restaurante---------------------//
     {
        id : 10,
        tipo : "restaurante",
        titulo : "Bad Burgers",
        imagenes : ["../Multimedia/Lugares/restaurantes/babburguers4.jpg", 
        "../Multimedia/Lugares/restaurantes/babbuders2.png",
         "../Multimedia/Lugares/restaurantes/babbuders1.png",],
        textDetalles : "Para aquellas personas amantes de las hambuerguesas, Bad Burgers cuenta con variedad de Burguers y otras comidas para deleitarte pasando un buen rato con tus acompañantes.",
        precio : "$5.000 - 25.000",
        horario : "",
        direccion : "Cra. 29 #42-57, La Milagrosa, Medellín, Buenos Aires, Medellín, Antioquia",
        linkDireccion : "",
        vr : "https://www.google.com/maps/@6.250017,-75.5675647,3a,75y,133.73h,116.15t/data=!3m8!1e1!3m6!1sAF1QipPjFEMdLkodAsIEaezawBpdEL7JBkAjlublrvF6!2e10!3e11!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipPjFEMdLkodAsIEaezawBpdEL7JBkAjlublrvF6%3Dw203-h100-k-no-pi0-ya336.6846-ro-0-fo100!7i8000!8i4000?entry=ttu",
        correo : "",
        web : "",
        telefono : ["3054217782",""],
        puntuacion : "4,7 ★ ★ ★ ★",
        opiniones : "44 Opiniones",
        usuarios : ["Neithan  👤","Felipe   👤","Magalys   👤"],
        comentarios : ["Excelente todo, las hamburguesas deliciosas y muy baratas, las papas fritas frescas y ricas, la malteada muy buena, la atención muy rápida y amable. Super recomendado.",
        "Un buen lugar para compartir en familia. La atención es buena y los productos son muy frescos.",
        "Es una buena hamburguesa económica..buen servicio... excelente atención... necesitan un local más grande tienen mucha acogida en el sector",],
        imagenMenu : "",
        BtnConoce : "https://www.rappi.com.co/restaurantes/900368326-bad-burgers?utm_source=google&utm_medium=organic&utm_campaign=place-action-link",
        
    },
    {  //19
        id : 11,
        tipo : "restaurante",
        titulo : "Hacienda el Origen",
        imagenes : ["../Multimedia/Lugares/restaurantes/Hacienda/hacienda (2).jpeg",
         "..\Multimedia\Lugares\restaurantes\Hacienda\hacienda2.jpeg", 
         "../Multimedia\Lugares\restaurantes\Hacienda\hacienda3.jpeg",],
        textDetalles : "",
        precio : "",
        horario : "",
        direccion : "",
        linkDireccion : "",
        vr : "",
        correo : "",
        web : "",
        telefono : ["",""],
        puntuacion : "",
        opiniones : "",
        usuarios : ["Juan   👤","Brailer   👤","Jenny   👤"],
        comentarios : ["","","",],
        imagenMenu : "",
        BtnConoce : "",
        
    },
    {  //19
        id : 12,
        tipo : "restaurante",
        titulo : "Pigasus",
        imagenes : ["../Multimedia/Lugares/restaurantes/Pigasus/pigasus3.jpg", "", "",],
        textDetalles : "",
        precio : "",
        horario : "",
        direccion : "",
        linkDireccion : "",
        vr : "",
        correo : "",
        web : "",
        telefono : ["",""],
        puntuacion : "",
        opiniones : "",
        usuarios : ["Juan   👤","Brailer   👤","Jenny   👤"],
        comentarios : ["","","",],
        imagenMenu : "",
        BtnConoce : "",
        
    },
    //-----------------------hospedajes-----------------//
    {  //19
        id : 13,
        tipo : "hospedaje",
        titulo : "Alojamiento laureles estadio Medellín",
        imagenes : ["../Multimedia/Lugares/Alojamiento/laureles/Alo.1.jpg", "../Multimedia/Lugares/Alojamiento/laureles/Alo.1.jpg", "",],
        textDetalles : `Apartamento de una habitación que incluye: <br>
        Cama doble <br>
        Baño Privado <br> 
        Cocina Equipada <br> 
        TV plana <br> 
        Lavadora <br>
        Wifi <br>`,
        precio : "($135.000 - $150.000)",
        horario : "",
        direccion : "Cra 77A #49-23, Laureles - Estadio, Medellín, Laureles, Medellín, Antioquia",
        linkDireccion : "",
        vr : "https://www.google.com/maps/@6.2604175,-75.5933761,3a,90y,325.22h,88.76t/data=!3m7!1e1!3m5!1sl3x2N-DscCF2t6COp0GYLg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3Dl3x2N-DscCF2t6COp0GYLg%26cb_client%3Dsearch.gws-prod.gps%26w%3D360%26h%3D120%26yaw%3D319.9411%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192?entry=ttu",
        correo : "",
        web : "",
        telefono : ["",""],
        puntuacion : "3,0 ★ ★ ★",
        opiniones : "120 opiniones",
        usuarios : ["Pablo   👤","Esteban   👤","yulisa   👤"],
        comentarios : ["La habitacion es algo pequeña, pero aparte de eso cuentan buena atencion al cliente. Me gusto!",
        "El hospedaje estuvo bien, si debo recomendar algo es que mejores las habitaciones y ponga el parqueadero grartis.",
        "La Habitación es pequeña, el baño se comparte y si llevas carro te cobran un excedente, por el mismo precio se consigue en el sector mejores y mas modernos",],
        informacion : ["Alojamiento laureles estadio medellin se encuentra a 7,9 km de Parque El Poblado y ofrece alojamiento con patio y wifi gratis.",
        "Todas las unidades cuentan con TV de pantalla plana y cocina totalmente equipada con nevera, fogones y cafetera. Para mayor comodidad, el alojamiento puede ofrecer toallas y ropa de cama por un suplemento.",
         "Parque Lleras está a 8,9 km del alojamiento, y Segundo Parque Laureles está a 2,4 km. El aeropuerto (Aeropuerto Olaya Herrera) está a 5 km, y el alojamiento ofrece servicio de traslado de pago para ir o volver del aeropuerto."],
        BtnConoce : "",
        
    },
    {  //19
        id : 14,
        tipo : "hospedaje",
        titulo : "Hastags98",
        imagenes : ["../Multimedia/Lugares/Alojamiento/Hastags98/alo3.jpg", "", "",],
        textDetalles : "",
        precio : "",
        horario : "",
        direccion : "",
        linkDireccion : "",
        vr : "",
        correo : "",
        web : "",
        telefono : ["",""],
        puntuacion : "",
        opiniones : "",
        usuarios : ["Juan   👤","Brailer   👤","Jenny   👤"],
        comentarios : ["","","",],
        informacion : ["",""],
        BtnConoce : "",
        
    },
    {  //19
        id : 15,
        tipo : "hospedaje",
        titulo : "Boutique",
        imagenes : ["../Multimedia/Lugares/Alojamiento/Boutique/alo2.2.jpg", "", "",],
        textDetalles : "",
        precio : "",
        horario : "",
        direccion : "",
        linkDireccion : "",
        vr : "",
        correo : "",
        web : "",
        telefono : ["",""],
        puntuacion : "",
        opiniones : "",
        usuarios : ["Juan   👤","Brailer   👤","Jenny   👤"],
        comentarios : ["","","",],
        informacion : ["",""],
        BtnConoce : "",
        
    },

]
        
