import type { Metadata } from "next";
import "./../styles/globals.css";
import { SelectProvider } from "@/context/SelectContext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`w-screen h-screen`}>
          <SelectProvider>
            {children}
          </SelectProvider>
      </body>
    </html>
  );
}
