
export const DataImg=[
/*   {
    id:,
    nombre:"",
    ubicacion: "",
    etiquetas:["","","",""],
    decripcion: "",  
  }
  */
  {//Cementerio Museo de San Pedro
    id: 1.1,
    nombre:"Cementerio Museo de San Pedro",
    ubicacion: "../Multimedia/Lugares/cultura/Cemuseo/Cementerio.jpg",
    etiquetas:"cultura",
    decripcion: "Imagina sumergirte en un viaje fascinante a través del tiempo y la historia en el Cementerio que encierra los secretos más sorprendentes del patrimonio cultural y artístico de Medellín.",  
  },
  {
    id: 1.2,
    nombre:"Cementerio Museo de San Pedro",
    ubicacion: "../Multimedia/Lugares/cultura/Cemuseo/Cementerio2.jpg",
    etiquetas:["cultura","historia","diseño arquitectónico", "museo","cementerio"],
    decripcion: "!Explora la belleza inexplorada de este legado funerario único y déjate envolver por la majestuosidad de cada monumento!", 
  },
  {
    id: 1.3,
    nombre:"Cementerio Museo de San Pedro",
    ubicacion: "../Multimedia/Lugares/cultura/Cemuseo/Cementerio3.jpg",
    etiquetas:["cultura","historia","naturaleza","diseño arquitectónico","museo","cementerio"],
    decripcion: "Explora Medellín, descubre la historia y arte de la ciudad en su famoso Cementerio lleno de figuras que marcaron un antes y después en la región.",  
  },
  {// Palacio de la Cultura
    id: 2.1,
    nombre:"Palacio de la cultura Rafael Ubire",
    ubicacion: "../Multimedia/Lugares/cultura/Palacio Rafael Uribe Cultura/PalacioUribe.jpg",
    etiquetas:["historia","cultura","diseño arquitectónico","arte", "Antiguedad"],
    decripcion: "Sumérgete en la vibrante vida cultural del corazón de la ciudad, donde el Palacio Rafael Uribe alberga tesoros históricos y artísticos de la Ciudad.",  
  },
  {
    id: 2.2,
    nombre:"Palacio de la cultura Rafael Ubire",
    ubicacion: "../Multimedia/Lugares/cultura/Palacio Rafael Uribe Cultura/PalacioUribe2.jpg",
    etiquetas:["historia","cultura","diseño arquitectónico","arte", "Antiguedad"],
    decripcion: "Descubre Antioquia a través de su patrimonio artístico, una experiencia enriquecedora que te conectará con la esencia cultural de la región.",  
  },
  {
    id: 2.3,
    nombre:"Palacio de la cultura Rafael Ubire",
    ubicacion: "../Multimedia/Lugares/cultura/Palacio Rafael Uribe Cultura/PalacioUribe3.jpg",
    etiquetas:["historia","cultura","diseño arquitectónico","arte", "Antiguedad"],
    decripcion: "Embárcate en un viaje cultural en el epicentro de la ciudad, donde el Palacio Rafael Uribe se erige como un tesoro multifacético.",  
  },
  {//Museo de La Memoria
    id: 3.1,
    nombre:"Museo Casa de la Memoria",
    ubicacion: "../Multimedia/Lugares/cultura/Museo Casa de la Memoria/Museo.jpg",
    etiquetas:["historia","cultura","diseño arquitectónico","museo"],
    decripcion: "Sumérgete en una experiencia conmovedora , donde las víctimas del conflicto armado convergen para crear y preservar sus historias.",  
  },
  {
    id: 3.2,
    nombre:"Museo Casa de la Memoria",
    ubicacion: "../Multimedia/Lugares/cultura/Museo Casa de la Memoria/Museo2.jpg",
    etiquetas:["historia","cultura","diseño arquitectónico","museo"],
    decripcion: "Sumérgete en el Museo de la Memoria en Colombia, donde las historias de valentía y resistencia se entrelazan para tejer un tapiz de esperanza.",  
  },
  {
    id: 3.3,
    nombre:"Museo Casa de la Memoria",
    ubicacion: "../Multimedia/Lugares/cultura/Museo Casa de la Memoria/Museo3.jpg",
    etiquetas:["historia","cultura","diseño arquitectónico","museo"],
    decripcion: "Se parte de las comunidades unidas construyen paz a través de expresiones artísticas, preservando con amor y coraje las memorias de los conflictos.",  
  },
  {// Basi
    id: 4.1,
    nombre:"Basílica de Nuestra Señora de la Candelaria",
    ubicacion: "../Multimedia/Lugares/historia/basilica/Basilica-candelaria.jpeg",
    etiquetas:["historia","cultura","diseño arquitectónico","religion","iglesia"],
    decripcion: "Adéntrate en la esencia histórica y religiosa de la Basílica, el corazón que marca el inicio del legado católico de los Antioqueños."
  },
  {
    id: 4.2,
    nombre:"Basílica de Nuestra Señora de la Candelaria",
    ubicacion: "../Multimedia/Lugares/historia/basilica/basilica.jpg",
    etiquetas:["historia","cultura","religion","iglesia"],
    decripcion: "Una experiencia cautivadora para aficionados de la historia y la fe, que invita a explorar las raíces espirituales de la Región.",  
  },
  {
    id: 4.3,
    nombre:"Basílica de Nuestra Señora de la Candelaria",
    ubicacion: "../Multimedia/Lugares/historia/basilica/basilica4.jpg",
    etiquetas:["historia","cultura","religion","antiguiedad","iglesia"],
    decripcion: "Descubre la esencia única que envuelve a la Basílica, donde cada visita se convierte en un viaje de devoción y descubrimiento.",
  },
  {
    id: 4.4,
    nombre:"Basílica de Nuestra Señora de la Candelaria",
    ubicacion: "../Multimedia/Lugares/historia/basilica/candelaria.jpg",
    etiquetas:["historia","cultura","diseño arquitectónico","religion","antiguiedad","iglesia"],
    decripcion: "Descifra la fe en un recorrido de veneración y revelación al explorar las profundidades, cautivado por la singular esencia que abraza a la Basílica.",  
  },
  {// Museo El Castillo
    id: 5.1,
    nombre:"Museo el Castillo",
    ubicacion: "../Multimedia/Lugares/historia/MuseoCastillo/museo5.png",
    etiquetas:["historia","cultura","diseño arquitectónico","arte","antiguiedad","museo"],
    decripcion: "Sumérgete en la majestuosidad del arte gótico medieval en el Principal representante de la ciudad de Medellín!",  
  },
  {
    id: 5.2,
    nombre:"Museo el Castillo",
    ubicacion: "../Multimedia/Lugares/historia/MuseoCastillo/MuseoC.jpeg",
    etiquetas:["historia","cultura","diseño arquitectónico","arte","antiguiedad","museo"],
    decripcion: " Una experiencia única que te transportará a través de los siglos, invitándote a explorar la riqueza cultural y artística que este lugar icónico tiene para ofrecer.",  
  },
  {
    id: 5.3,
    nombre:"Museo el Castillo",
    ubicacion: "../Multimedia/Lugares/historia/MuseoCastillo/MuseoC2.jpeg",
    etiquetas:["historia","cultura","diseño arquitectónico","arte","antiguiedad","museo"],
    decripcion: "Explora la magnificencia en exposiciones con porcelanas, cristales, vitrales, tapices, reliquias, pinturas y esculturas cautivadoras en uno de los Centros Artísticos de la ciudad.",  
  },
  {
    id: 5.4,
    nombre:"Museo el Castillo",
    ubicacion: "../Multimedia/Lugares/historia/MuseoCastillo/MuseoC3.jpg",
    etiquetas:["historia","cultura","diseño arquitectónico","arte","antiguiedad","museo"],
    decripcion: "Abre las puertas a un mundo encantado donde el arte gótico medieval cobra vida en uno de los epicentros culturales Artísticos de la ciudad." ,
  },
  {//Parque Berrío
    id: 6.1,
    nombre:"Parque Berrío",
    ubicacion: "../Multimedia/Lugares/historia/parkBerrio/Pberrio.jpg",
    etiquetas:["historia","cultura","diseño arquitectónico","antiguiedad","plaza","parque"],
    decripcion: "Sumérgete en el corazón histórico de la urbe, un ícono urbano reverenciado por generaciones de antioqueños como el principal punto de encuentro.",
  },
  {
    id: 6.2,
    nombre:"Parque Berrío",
    ubicacion: "../Multimedia/Lugares/historia/parkBerrio/Pberrio2.jpg",
    etiquetas:["historia","cultura","diseño arquitectónico","arte","antiguiedad","museo"],
    decripcion: "Descubre la magia de este lugar, impregnado de significado, donde la historia se entrelaza con la identidad local." ,
  },
  {
    id: 6.3,
    nombre:"Parque Berrío",
    ubicacion: "../Multimedia/Lugares/historia/parkBerrio/Pberrio3.jpg",
    etiquetas:["historia","cultura","diseño arquitectónico","arte","antiguiedad","museo"],
    decripcion: "Sumérgete en la atmósfera única de este lugar impregnado de historia, donde cada rincón cuenta una historia y cada visita se convierte en un viaje fascinante a través del tiempo." ,
  },
  {
    id: 6.4,
    nombre:"Parque Berrío",
    ubicacion: "../Multimedia/Lugares/historia/parqueberrio/berrio3.png",
    etiquetas:["historia","cultura","diseño arquitectónico","arte","antiguiedad","museo"],
    decripcion: "",
  },
  {//Botánico
    id: 7.1,
    nombre:"Jardin Botánico",
    ubicacion: "../Multimedia/Lugares/naturaleza/Botanico/Botanico.webp",
    etiquetas:["cultura","naturaleza","diseño arquitectónico","parque"],
    decripcion: " Sumérgete en la naturaleza, aprendizaje y belleza que este lugar excepcional tiene para ofrecer.",
  },
  {
    id: 7.2,
    nombre:"Jardin Botánico",
    ubicacion: "../Multimedia/Lugares/naturaleza/Botanico/Botanico2.jpeg",
    etiquetas:["cultura","naturaleza","parque"],
    decripcion: "Verás algo más que una atracción turística, es un centro vital de cultura, educación ambiental y botánica.",
  },
  {
    id: 7.3,
    nombre:"Jardin Botánico",
    ubicacion: "../Multimedia/Lugares/naturaleza/Botanico/Botanico3.jpg",
    etiquetas:["cultura","naturaleza","parque"],
    decripcion: "Descubre la cautivadora experiencia en el Jardín Botánico con una de las mayores y más representativas reservas Naturales de la ciudad.",
  },
  {//Park Arví
    id: 8.1,
    nombre:"Parque Arví",
    ubicacion: "../Multimedia/Lugares/naturaleza/Parque Arvi/Arvi.jpeg",
    etiquetas:["naturaleza","diseño arquitectónico","parque","montaña"],
    decripcion: "Explora la magia del impresionante parque natural en las montañas, en este rincón lleno de actividades al aire libre, cada visita se convierte en una experiencia enriquecedora.",
  },
  {
    id: 8.2,
    nombre:"Parque Arví",
    ubicacion: "../Multimedia/Lugares/naturaleza/Parque Arvi/Arvi2.jpeg",
    etiquetas:["naturaleza","diseño arquitectónico","parque","montaña"],
    decripcion: "Descubre el paraíso natural a las puertas de Medellín, un impresionante parque que invita a los amantes de la naturaleza a escapar del estrés urbano.",
  },
  {
    id: 8.3,
    nombre:"Parque Arví",
    ubicacion: "../Multimedia/Lugares/naturaleza/Parque Arvi/Arvi3.jpg",
    etiquetas:["naturaleza","diseño arquitectónico","parque","montaña","rio"],
    decripcion: "Un santuario natural que se erige como el rincón perfecto para desconectar del trajín citadino te espera!",
  },
  {
    id: 8.4,
    nombre:"Parque Arví",
    ubicacion: "../Multimedia/Lugares/naturaleza/Parque Arvi/Arvi4.jpg",
    etiquetas:["naturaleza","parque","mirador","montaña","bosque"],
    decripcion: "Sumérgete en la serenidad del asombroso parque natural, un refugio en las montañas que se erige como el destino predilecto para escapar del bullicio urbano.",
  },
  {//Picachu
    id: 9.1,
    nombre:"Cerro el Picacho",
    ubicacion: "../Multimedia/Lugares/naturaleza/Picacho/Picacho.jpg",
    etiquetas:["naturaleza","parque","mirador","montaña","bosque"],
    decripcion: "Déjate cautivar por la magia de uno de los tesoros naturales de la ciudad, sumérgete en esta formación esculpida por la maestría de la naturaleza.",
  },
  {
    id: 9.2,
    nombre:"Cerro el Picacho",
    ubicacion: "../Multimedia/Lugares/naturaleza/Picacho/Picacho2.jpg",
    etiquetas:["parque","mirador","montaña","bosque","nocturno"],
    decripcion: "Embárcate en una aventura natural única, ofreciendo un escape sereno donde la armonía del entorno revela el legado artístico de la madre naturaleza.",
  },
  {
    id: 9.3,
    nombre:"Cerro el Picacho",
    ubicacion: "../Multimedia/Lugares/naturaleza/Picacho/Picacho3.jpg",
    etiquetas:["mirador","montaña","bosque","nocturno"],
    decripcion: "Despierta tú asombro, viviendo una experiencia donde la belleza y la serenidad convergen en cada sendero, revelando la creación artística de la madre tierra.",
  },
  {// Restaurants / Bad Burguers
    id: 10.1,
    nombre:"Bad Burgers",
    ubicacion: "../Multimedia/Lugares/restaurantes/babburguers4.jpg.",
    etiquetas:["restaurante","montaña","bosque","nocturno"],
    decripcion: "En Bad Burgers podrás disfrutar de una variedad irresistible de sabores y acompañamientos, mientras compartes momentos inolvidables con tus seres queridos. ",
  },
  //Pendiente por más multimedia +2 restaurantes



  //  Hospedajes - Alojamiento, Laureles Estadio
  //    id: 10.1,
  //    nombre:"Alojamiento laureles estadio Medellín",
  //    ubicacion: "../Multimedia/Lugares/restaurantes/babburguers4.jpg.jpg",
  //    etiquetas:["restaurante","montaña","bosque","nocturno"],
  //    decripcion: "En Bad Burgers podrás disfrutar de una variedad irresistible de sabores y acompañamientos, mientras compartes momentos inolvidables con tus seres queridos. ",
  //    Alojamientos descontinuados...
  
]